#!/bin/bash

function download_paper {
	# Download paper using the folowing tweak:
	# http://techqe.blogspot.com.br/2009/09/quick-download-ieee-paper.html
	# 	$1 - The paper ID
	#   Return the pdf metadata
	wget --progress=bar "http://ieeexplore.ieee.org/stampPDF/getPDF.jsp?tp=&isnumber=&arnumber=$1" -O $2/$1.pdf
}

function get_paper_title {
	T=$(pdfinfo /tmp/$1.pdf | grep Title: | sed s/Title://)
	echo $T
}

function get_paper_author {
	T=$(pdfinfo /tmp/$1.pdf | grep Author: | sed s/Author:// | cut -d',' -f1)
	echo $T
}

function get_paper_year {
	T=$(pdfinfo /tmp/$1.pdf | grep CreationDate | sed s/CreationDate:// | sed 's/ */ /')
	echo $T | cut -d" " -f5
}

function show_result {
	echo -e "\n:: The folowing paper was downloaded ::"
	echo -e "\t TITLE: $1"
	echo -e "\t AUTHOR: $2"
	echo -e "\t YEAR: $3\n"
}

if [ $# -eq 0 ]; then
	echo "The first argument must be the paper number"
	exit
else
	echo -e "\n:: Downloading Paper Info Please wait ::"
	download_paper $1 /tmp

	# Get some data from description file
	title=$(get_paper_title $1)
	authors=$(get_paper_author $1)
	year=$(get_paper_year $1)

	show_result "$title" "$authors" "$year"

	T="`echo $title | tr ' ' '-'`"; # Change spaces to -
	A="`echo $authors  | tr ' ' '-'`" # Get just the first author
	fileName="`echo $A\_$year\_$T`.pdf"

	echo "Creating: $fileName"
	cp /tmp/$1.pdf $fileName
fi

